In [6]:
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
data = pd.read_excel(r"C:\Users\Dell\Downloads\BMW_Cars.xlsx")
data

,Row_id,year,month,country,model,segment,engine_type,price_usd,marketing_spend_usd,dealership_count,fuel_price_usd,gdp_growth_percent,interest_rate_percent,competition_index,units_sold
0,1,2016-07-01,1,"Australia, Melbourne",X1,SUV,Petrol,82234,315372,96,0.97,6.29,1.2,8,324
1,2,2019-08-20,8,"Australia, Sydney",i4,Sedan,Electric,82291,447798,234,0.97,6.29,1.2,7,556
2,3,2020-05-21,12,"USA, Washington",5 Series,Electric,Hybrid,40594,259755,25,0.97,6.29,1.2,7,152
3,4,2015-06-03,11,"Australia, Adelaide",i7,SUV,Electric,42371,323541,319,0.97,6.29,1.2,5,730
4,5,2015-01-29,12,"Brazil, Brasília",X5,SUV,Diesel,82315,482015,367,0.97,6.29,1.2,2,1156
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,2019-06-29,7,"USA, Washington",3 Series,Sedan,Hybrid,62241,403972,198,0.97,6.29,1.2,8,508
96,97,2015-06-16,3,"China, Bajing",i7,Electric,Diesel,50540,348276,355,0.97,6.29,1.2,5,1177
97,98,2017-12-27,11,"Canada, Toronto",3 Series,SUV,Hybrid,107255,427864,239,0.97,6.29,1.2,6,630
98,99,2021-12-20,8,"Brazil, Salvador",i4,SUV,Diesel,99757,348254,264,0.97,6.29,1.2,1,845
99,100,2023-10-18,3,"Japan, Tokyo",X3,SUV,Electric,76203,239826,245,0.97,6.29,1.2,6,880

In [8]:
drop_column = data.drop(columns=["month"],inplace=True)
data

,Row_id,year,country,model,segment,engine_type,price_usd,marketing_spend_usd,dealership_count,fuel_price_usd,gdp_growth_percent,interest_rate_percent,competition_index,units_sold
0,1,2016-07-01,"Australia, Melbourne",X1,SUV,Petrol,82234,315372,96,0.97,6.29,1.2,8,324
1,2,2019-08-20,"Australia, Sydney",i4,Sedan,Electric,82291,447798,234,0.97,6.29,1.2,7,556
2,3,2020-05-21,"USA, Washington",5 Series,Electric,Hybrid,40594,259755,25,0.97,6.29,1.2,7,152
3,4,2015-06-03,"Australia, Adelaide",i7,SUV,Electric,42371,323541,319,0.97,6.29,1.2,5,730
4,5,2015-01-29,"Brazil, Brasília",X5,SUV,Diesel,82315,482015,367,0.97,6.29,1.2,2,1156
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,2019-06-29,"USA, Washington",3 Series,Sedan,Hybrid,62241,403972,198,0.97,6.29,1.2,8,508
96,97,2015-06-16,"China, Bajing",i7,Electric,Diesel,50540,348276,355,0.97,6.29,1.2,5,1177
97,98,2017-12-27,"Canada, Toronto",3 Series,SUV,Hybrid,107255,427864,239,0.97,6.29,1.2,6,630
98,99,2021-12-20,"Brazil, Salvador",i4,SUV,Diesel,99757,348254,264,0.97,6.29,1.2,1,845
99,100,2023-10-18,"Japan, Tokyo",X3,SUV,Electric,76203,239826,245,0.97,6.29,1.2,6,880

In [9]:
rename_coloumn = data.rename(columns={"year":"Date"},inplace=True)
data

,Row_id,Date,country,model,segment,engine_type,price_usd,marketing_spend_usd,dealership_count,fuel_price_usd,gdp_growth_percent,interest_rate_percent,competition_index,units_sold
0,1,2016-07-01,"Australia, Melbourne",X1,SUV,Petrol,82234,315372,96,0.97,6.29,1.2,8,324
1,2,2019-08-20,"Australia, Sydney",i4,Sedan,Electric,82291,447798,234,0.97,6.29,1.2,7,556
2,3,2020-05-21,"USA, Washington",5 Series,Electric,Hybrid,40594,259755,25,0.97,6.29,1.2,7,152
3,4,2015-06-03,"Australia, Adelaide",i7,SUV,Electric,42371,323541,319,0.97,6.29,1.2,5,730
4,5,2015-01-29,"Brazil, Brasília",X5,SUV,Diesel,82315,482015,367,0.97,6.29,1.2,2,1156
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,2019-06-29,"USA, Washington",3 Series,Sedan,Hybrid,62241,403972,198,0.97,6.29,1.2,8,508
96,97,2015-06-16,"China, Bajing",i7,Electric,Diesel,50540,348276,355,0.97,6.29,1.2,5,1177
97,98,2017-12-27,"Canada, Toronto",3 Series,SUV,Hybrid,107255,427864,239,0.97,6.29,1.2,6,630
98,99,2021-12-20,"Brazil, Salvador",i4,SUV,Diesel,99757,348254,264,0.97,6.29,1.2,1,845
99,100,2023-10-18,"Japan, Tokyo",X3,SUV,Electric,76203,239826,245,0.97,6.29,1.2,6,880

In [31]:
data["Month"] = data["Date"].dt.month_name()
data["Year"] = data["Date"].dt.year
data

,Row_id,Date,country,model,segment,engine_type,price_usd,marketing_spend_usd,dealership_count,fuel_price_usd,gdp_growth_percent,interest_rate_percent,competition_index,units_sold,month,Month,Year
0,1,2016-07-01,"Australia, Melbourne",X1,SUV,Petrol,82234,315372,96,0.97,6.29,1.2,8,324,2016-07-01,July,2016
1,2,2019-08-20,"Australia, Sydney",i4,Sedan,Electric,82291,447798,234,0.97,6.29,1.2,7,556,2019-08-20,August,2019
2,3,2020-05-21,"USA, Washington",5 Series,Electric,Hybrid,40594,259755,25,0.97,6.29,1.2,7,152,2020-05-21,May,2020
3,4,2015-06-03,"Australia, Adelaide",i7,SUV,Electric,42371,323541,319,0.97,6.29,1.2,5,730,2015-06-03,June,2015
4,5,2015-01-29,"Brazil, Brasília",X5,SUV,Diesel,82315,482015,367,0.97,6.29,1.2,2,1156,2015-01-29,January,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,2019-06-29,"USA, Washington",3 Series,Sedan,Hybrid,62241,403972,198,0.97,6.29,1.2,8,508,2019-06-29,June,2019
96,97,2015-06-16,"China, Bajing",i7,Electric,Diesel,50540,348276,355,0.97,6.29,1.2,5,1177,2015-06-16,June,2015
97,98,2017-12-27,"Canada, Toronto",3 Series,SUV,Hybrid,107255,427864,239,0.97,6.29,1.2,6,630,2017-12-27,December,2017
98,99,2021-12-20,"Brazil, Salvador",i4,SUV,Diesel,99757,348254,264,0.97,6.29,1.2,1,845,2021-12-20,December,2021
99,100,2023-10-18,"Japan, Tokyo",X3,SUV,Electric,76203,239826,245,0.97,6.29,1.2,6,880,2023-10-18,October,2023

In [32]:
Drop_month = data.drop(columns={"month"},inplace=True)
data

,Row_id,Date,country,model,segment,engine_type,price_usd,marketing_spend_usd,dealership_count,fuel_price_usd,gdp_growth_percent,interest_rate_percent,competition_index,units_sold,Month,Year
0,1,2016-07-01,"Australia, Melbourne",X1,SUV,Petrol,82234,315372,96,0.97,6.29,1.2,8,324,July,2016
1,2,2019-08-20,"Australia, Sydney",i4,Sedan,Electric,82291,447798,234,0.97,6.29,1.2,7,556,August,2019
2,3,2020-05-21,"USA, Washington",5 Series,Electric,Hybrid,40594,259755,25,0.97,6.29,1.2,7,152,May,2020
3,4,2015-06-03,"Australia, Adelaide",i7,SUV,Electric,42371,323541,319,0.97,6.29,1.2,5,730,June,2015
4,5,2015-01-29,"Brazil, Brasília",X5,SUV,Diesel,82315,482015,367,0.97,6.29,1.2,2,1156,January,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,2019-06-29,"USA, Washington",3 Series,Sedan,Hybrid,62241,403972,198,0.97,6.29,1.2,8,508,June,2019
96,97,2015-06-16,"China, Bajing",i7,Electric,Diesel,50540,348276,355,0.97,6.29,1.2,5,1177,June,2015
97,98,2017-12-27,"Canada, Toronto",3 Series,SUV,Hybrid,107255,427864,239,0.97,6.29,1.2,6,630,December,2017
98,99,2021-12-20,"Brazil, Salvador",i4,SUV,Diesel,99757,348254,264,0.97,6.29,1.2,1,845,December,2021
99,100,2023-10-18,"Japan, Tokyo",X3,SUV,Electric,76203,239826,245,0.97,6.29,1.2,6,880,October,2023

In [34]:
data[["Country","City"]] = data["country"].str.split(",",expand=True)
data

,Row_id,Date,country,model,segment,engine_type,price_usd,marketing_spend_usd,dealership_count,fuel_price_usd,gdp_growth_percent,interest_rate_percent,competition_index,units_sold,Month,Year,Country,City
0,1,2016-07-01,"Australia, Melbourne",X1,SUV,Petrol,82234,315372,96,0.97,6.29,1.2,8,324,July,2016,Australia,Melbourne
1,2,2019-08-20,"Australia, Sydney",i4,Sedan,Electric,82291,447798,234,0.97,6.29,1.2,7,556,August,2019,Australia,Sydney
2,3,2020-05-21,"USA, Washington",5 Series,Electric,Hybrid,40594,259755,25,0.97,6.29,1.2,7,152,May,2020,USA,Washington
3,4,2015-06-03,"Australia, Adelaide",i7,SUV,Electric,42371,323541,319,0.97,6.29,1.2,5,730,June,2015,Australia,Adelaide
4,5,2015-01-29,"Brazil, Brasília",X5,SUV,Diesel,82315,482015,367,0.97,6.29,1.2,2,1156,January,2015,Brazil,Brasília
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,2019-06-29,"USA, Washington",3 Series,Sedan,Hybrid,62241,403972,198,0.97,6.29,1.2,8,508,June,2019,USA,Washington
96,97,2015-06-16,"China, Bajing",i7,Electric,Diesel,50540,348276,355,0.97,6.29,1.2,5,1177,June,2015,China,Bajing
97,98,2017-12-27,"Canada, Toronto",3 Series,SUV,Hybrid,107255,427864,239,0.97,6.29,1.2,6,630,December,2017,Canada,Toronto
98,99,2021-12-20,"Brazil, Salvador",i4,SUV,Diesel,99757,348254,264,0.97,6.29,1.2,1,845,December,2021,Brazil,Salvador
99,100,2023-10-18,"Japan, Tokyo",X3,SUV,Electric,76203,239826,245,0.97,6.29,1.2,6,880,October,2023,Japan,Tokyo

In [37]:
# Remove_column = data.drop(columns={"country"},inplace=True)
data

,Row_id,Date,model,segment,engine_type,price_usd,marketing_spend_usd,dealership_count,fuel_price_usd,gdp_growth_percent,interest_rate_percent,competition_index,units_sold,Month,Year,Country,City
0,1,2016-07-01,X1,SUV,Petrol,82234,315372,96,0.97,6.29,1.2,8,324,July,2016,Australia,Melbourne
1,2,2019-08-20,i4,Sedan,Electric,82291,447798,234,0.97,6.29,1.2,7,556,August,2019,Australia,Sydney
2,3,2020-05-21,5 Series,Electric,Hybrid,40594,259755,25,0.97,6.29,1.2,7,152,May,2020,USA,Washington
3,4,2015-06-03,i7,SUV,Electric,42371,323541,319,0.97,6.29,1.2,5,730,June,2015,Australia,Adelaide
4,5,2015-01-29,X5,SUV,Diesel,82315,482015,367,0.97,6.29,1.2,2,1156,January,2015,Brazil,Brasília
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,2019-06-29,3 Series,Sedan,Hybrid,62241,403972,198,0.97,6.29,1.2,8,508,June,2019,USA,Washington
96,97,2015-06-16,i7,Electric,Diesel,50540,348276,355,0.97,6.29,1.2,5,1177,June,2015,China,Bajing
97,98,2017-12-27,3 Series,SUV,Hybrid,107255,427864,239,0.97,6.29,1.2,6,630,December,2017,Canada,Toronto
98,99,2021-12-20,i4,SUV,Diesel,99757,348254,264,0.97,6.29,1.2,1,845,December,2021,Brazil,Salvador
99,100,2023-10-18,X3,SUV,Electric,76203,239826,245,0.97,6.29,1.2,6,880,October,2023,Japan,Tokyo

In [40]:
data

,Row_id,Date,model,segment,engine_type,price_usd,marketing_spend_usd,dealership_count,fuel_price_usd,gdp_growth_percent,interest_rate_percent,competition_index,units_sold,Year,Country,City,Month
0,1,2016-07-01,X1,SUV,Petrol,82234,315372,96,0.97,6.29,1.2,8,324,2016,Australia,Melbourne,July
1,2,2019-08-20,i4,Sedan,Electric,82291,447798,234,0.97,6.29,1.2,7,556,2019,Australia,Sydney,August
2,3,2020-05-21,5 Series,Electric,Hybrid,40594,259755,25,0.97,6.29,1.2,7,152,2020,USA,Washington,May
3,4,2015-06-03,i7,SUV,Electric,42371,323541,319,0.97,6.29,1.2,5,730,2015,Australia,Adelaide,June
4,5,2015-01-29,X5,SUV,Diesel,82315,482015,367,0.97,6.29,1.2,2,1156,2015,Brazil,Brasília,January
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,2019-06-29,3 Series,Sedan,Hybrid,62241,403972,198,0.97,6.29,1.2,8,508,2019,USA,Washington,June
96,97,2015-06-16,i7,Electric,Diesel,50540,348276,355,0.97,6.29,1.2,5,1177,2015,China,Bajing,June
97,98,2017-12-27,3 Series,SUV,Hybrid,107255,427864,239,0.97,6.29,1.2,6,630,2017,Canada,Toronto,December
98,99,2021-12-20,i4,SUV,Diesel,99757,348254,264,0.97,6.29,1.2,1,845,2021,Brazil,Salvador,December
99,100,2023-10-18,X3,SUV,Electric,76203,239826,245,0.97,6.29,1.2,6,880,2023,Japan,Tokyo,October

In [47]:
# Change the Date column only date formating
data["Date"] = pd.to_datetime(data["Date"]).astype("date32[pyarrow]")
data

,Row_id,Date,model,segment,engine_type,price_usd,marketing_spend_usd,dealership_count,fuel_price_usd,gdp_growth_percent,interest_rate_percent,competition_index,units_sold,Year,Country,City,Month
0,1,2016-07-01,X1,SUV,Petrol,82234,315372,96,0.97,6.29,1.2,8,324,2016,Australia,Melbourne,July
1,2,2019-08-20,i4,Sedan,Electric,82291,447798,234,0.97,6.29,1.2,7,556,2019,Australia,Sydney,August
2,3,2020-05-21,5 Series,Electric,Hybrid,40594,259755,25,0.97,6.29,1.2,7,152,2020,USA,Washington,May
3,4,2015-06-03,i7,SUV,Electric,42371,323541,319,0.97,6.29,1.2,5,730,2015,Australia,Adelaide,June
4,5,2015-01-29,X5,SUV,Diesel,82315,482015,367,0.97,6.29,1.2,2,1156,2015,Brazil,Brasília,January
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,2019-06-29,3 Series,Sedan,Hybrid,62241,403972,198,0.97,6.29,1.2,8,508,2019,USA,Washington,June
96,97,2015-06-16,i7,Electric,Diesel,50540,348276,355,0.97,6.29,1.2,5,1177,2015,China,Bajing,June
97,98,2017-12-27,3 Series,SUV,Hybrid,107255,427864,239,0.97,6.29,1.2,6,630,2017,Canada,Toronto,December
98,99,2021-12-20,i4,SUV,Diesel,99757,348254,264,0.97,6.29,1.2,1,845,2021,Brazil,Salvador,December
99,100,2023-10-18,X3,SUV,Electric,76203,239826,245,0.97,6.29,1.2,6,880,2023,Japan,Tokyo,October